name: 'Update downstream environment branches'
run-name: 'Update downstream environment branches'
on:
  schedule:
    - cron: '0 0 * * 1-5' # At 00:00, Monday through Friday
  workflow_dispatch:

permissions:
  contents: 'write'

jobs:
  merge-main-to-staging:
    name: 'Create merge PR from main to staging.'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout main'
        uses: 'actions/checkout@v4'
        with:
          ref: 'main'

      - name: 'Create new branch'
        shell: 'bash'
        run: |
          git config --global user.name 'Sofie Bot'
          git config --global user.email 'sofie-bot@users.noreply.github.com'
          git fetch --all && git pull --all
          git switch -c automerge/main-to-staging || git switch automerge/main-to-staging && git merge main
          git push -u origin automerge/main-to-staging

      - name: 'Create automerge PR'
        uses: './.github/actions/branch-sync'
        with:
          source_branch: 'automerge/main-to-staging'
          target_branch: 'staging'
          pr_title: 'Automerge `main` into `staging`'
          pr_description: 'Move changes from `main` to `staging`.'

  merge-staging-to-develop:
    name: 'Create merge PR from staging to develop.'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout staging'
        uses: 'actions/checkout@v4'
        with:
          ref: 'staging'

      - name: 'Create new branch'
        shell: 'bash'
        run: |
          git config --global user.name 'Sofie Bot'
          git config --global user.email 'sofie-bot@users.noreply.github.com'
          git fetch --all && git pull --all
          git switch -c automerge/staging-to-develop || git switch automerge/staging-to-develop && git merge staging
          git push -u origin automerge/staging-to-develop

      - name: 'Create automerge PR'
        uses: './.github/actions/branch-sync'
        with:
          source_branch: 'automerge/staging-to-develop'
          target_branch: 'develop'
          pr_title: 'Automerge `staging` into `develop`'
          pr_description: 'Move changes from `staging` to `develop`.'
