name: 'Update downstream environment branches2'
run-name: 'Update downstream environment branches2'
on:
  schedule:
    - cron: '0 0 * * 1-5' # At 00:00, Monday through Friday
  workflow_dispatch:

permissions:
  contents: 'write'

jobs:
  merge-main-to-staging:
    name: 'Create merge PR for main to staging'
    runs-on: 'ubuntu-latest'
    steps:
        - uses: 'actions/checkout@v4'

        - name: 'Set Git config'
          run: |
            git config --local user.name "GitHub Actions # Sofie bot"
            git config --local user.email "sofie-bot@users.noreply.github.com"

        - name: 'Create merge PR from main to staging'
          uses: 'repo-sync/pull-request@v2'
          with:
            source_branch: 'main'
            destination_branch: 'staging'
            pr_title: 'Merge _main_ into _staging_'
            pr_body: |
              Branch _main_ has changes not on _staging_ branch.
              Merging this pull request will apply the changes to the _staging_ branch.
            github_token: ${{ github.token }}

  merge-staging-to-develop:
    name: 'Create merge PR from staging to develop'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Set Git config'
        run: |
          git config --local user.name "GitHub Actions # Sofie bot"
          git config --local user.email "sofie-bot@users.noreply.github.com"

      - name: 'Create merge PR from staging to develop'
        uses: 'repo-sync/pull-request@v2'
        with:
          source_branch: 'staging'
          destination_branch: 'develop'
          pr_title: 'Merge _staging_ into _develop_'
          pr_body: |
            Branch _staging_ has changes not on _develop_ branch.
            Merging this pull request will apply the changes to the _develop_ branch.
          github_token: ${{ github.token }}
