name: Increment
on:
  workflow_dispatch:
    inputs:
      incrementType:
        description: 'Increment type:'
        type: 'choice'
        required: true
        options:
          - 'major'
          - 'minor'
          - 'patch'
jobs:
  increment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - run: yarn version ${{ github.inputs.incrementType }}
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

