name: Increment
on:
  workflow_dispatch:
    inputs:
      incrementType:
        description: 'Increment type:'
        type: 'choice'
        required: true
        options:
          - 'major'
          - 'minor'
          - 'patch'
jobs:
  increment:
    runs-on: 'ubuntu-latest'
    steps:
      - run: yarn install
      - run: yarn version ${{ github.inputs.incrementType }}
      - name: Commit & Push changes
        uses: actions-js/push@master

